server:
  port: 8000
spring:
  config:
    import: "optional:configserver:"
    activate:
      on-profile: local,dev,prod
  application:
    name: apigateway-service
  cloud:
    config:
      name: apigateway-service
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Expose-Headers
      routes:
        ## member service
        # White List
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/actuator/health,/member-service/api/sign-up,/member-service/api/sign-in,/member-service/api/members/isDuplicated
            - Method=GET,POST,OPTIONS
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        # Black List
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        ## delivery service
        # White List
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery-service/actuator/health
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - RewritePath=/delivery-service/(?<segment>.*), /$\{segment}
        # Black List
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery-service/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - RewritePath=/delivery-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        ## notification service
        # White List
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification-service/actuator/health
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - RewritePath=/notification-service/(?<segment>.*), /$\{segment}
        # Black List
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification-service/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - RewritePath=/notification-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        ## project service
        # White List
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/project-service/actuator/health,
              /project-service/api/projects/banner,
              /project-service/api/projects,
              /project-service/api/projects/lotdeal,
              /project-service/api/projects/category/{variable:.*},
              /project-service/api/projects/special-exhibition,
              /project-service/api/projects/{variable:.*},
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - RewritePath=/project-service/(?<segment>.*), /$\{segment}
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/project-service/api/projects/{variable:.*}/support-signature
            - Method=GET
          filters:
            - RewritePath=/project-service/(?<segment>.*), /$\{segment}

        # Black List
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/project-service/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - RewritePath=/project-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        ## payment service
        # White List
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/actuator/health,/payment-service/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - RewritePath=/payment-service/(?<segment>.*), /$\{segment}
        # Black List
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - RewritePath=/payment-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        ## funding service
        # White List
        - id: funding-service
          uri: lb://FUNDING-SERVICE
          predicates:
            - Path=/funding-service/actuator/health,/funding-service/api/projects/{variable:.*}/supporter-with-us
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - RewritePath=/funding-service/(?<segment>.*), /$\{segment}
        # Black List
        - id: funding-service
          uri: lb://FUNDING-SERVICE
          predicates:
            - Path=/funding-service/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - RewritePath=/funding-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        ## admin service
        # White List
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin-service/actuator/health
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - RewritePath=/admin-service/(?<segment>.*), /$\{segment}
        # Black List
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin-service/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - RewritePath=/admin-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        ## config service
        - id: config-service
          uri: lb://CONFIG-SERVICE
          predicates:
            - Path=/config-service/**
            - Method=GET,POST,OPTIONS
          filters:
            - RewritePath=/config-service/(?<segment>.*), /$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh