server:
  port: 8000
spring:
  config:
    activate:
      on-profile: local,dev,prod
  application:
    name: apigateway-service
  cloud:
    config:
      name: apigateway-service
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - http://localhost:5173
              - http://127.0.0.1:5173
            allow-credentials: true
            allowedHeaders:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
      routes:
        # member service
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/api/sign-up # 회원가입
            - Method=GET,POST,OPTIONS
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/api/sign-in # 로그인
            - Method=GET,POST
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        # delivery service
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/delivery-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        # notification service
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/notification-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        # project service
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/project-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/project-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        # payment service
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/payment-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        # funding service
        - id: funding-service
          uri: lb://FUNDING-SERVICE
          predicates:
            - Path=/funding-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/funding-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        # admin service
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/admin-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        # config service
        - id: config-service
          uri: lb://CONFIG-SERVICE
          predicates:
            - Path=/config-service/**
            - Method=GET,POST
          filters:
            - RewritePath=/config-service/(?<segment>.*), /$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh